name: workspace
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

workspace:
  - packages/cinema
  - packages/cinema_core
  - packages/cinema/example
  - packages/cinema_android
  - packages/cinema_darwin

dev_dependencies:
  flutter_lints: ^6.0.0
